### ISSUE TITLE
数据库文件

### ISSUE THREAD

**Issue by jimmyrick** [GitHub1he/kob#2]
请问作者数据库文件在哪啊，找了半天没看见，请问能提供一下吗

**Comment by GitHub1he** [comment]
我是在https://www.acwing.com/这个网站学习并对项目进行扩展的
您对该项目感兴趣我很高兴，以下为本项目所使用到的sql语句
create table bot
(
    id          int auto_increment
        primary key,
    user_id     int            not null,
    title       varchar(30)    null,
    description varchar(300)   null,
    content     varchar(10000) null,
    createtime  datetime       null,
    modifytime  datetime       null,
    constraint id
        unique (id)
);

create table chat
(
    id          int auto_increment
        primary key,
    sender_id   int           null,
    receiver_id int           null,
    content     varchar(1000) null,
    status      int default 0 null,
    sendtime    datetime      null,
    modifytime  datetime      null,
    constraint id
        unique (id)
);

create table friends
(
    id          int auto_increment
        primary key,
    target_id   int not null,
    follower_id int not null
);

create table posts
(
    id         int auto_increment
        primary key,
    user_id    int           null,
    post       varchar(1000) null,
    likes      int default 0 null,
    is_private int default 1 null,
    createtime datetime      null,
    modifytime datetime      null
);

create table record
(
    id         int auto_increment
        primary key,
    a_id       int           null,
    a_sx       int           null,
    a_sy       int           null,
    b_id       int           null,
    b_sx       int           null,
    b_sy       int           null,
    a_steps    varchar(1000) null,
    b_steps    varchar(1000) null,
    map        varchar(1000) null,
    winer      varchar(10)   null,
    createtime datetime      null,
    constraint id
        unique (id)
);

create table teams
(
    id           int auto_increment
        primary key,
    name         varchar(20)                                                                                     not null,
    photo        varchar(100) default 'url' null,
    owner_id     int                                                                                             null,
    person_count int                                                                                             null,
    createtime   datetime                                                                                        null,
    modifytime   datetime                                                                                        null,
    constraint id
        unique (id)
);

create table teams_detail
(
    id        int auto_increment
        primary key,
    team_id   int      null,
    user_id   int      null,
    join_time datetime null,
    constraint id
        unique (id)
);

create table user
(
    id              int auto_increment
        primary key,
    name            varchar(20)      not null,
    password        varchar(100)     null,
    photo           varchar(200)     null,
    followerCount   int default 0    null,
    rating          int default 1500 null,
    last_login_time datetime         null
);
